{
 "title": "OS Level Metrics",
 "description": "Requires Node Exporter (https://github.com/prometheus/node_exporter) to be installed on the nodes to be monitored.",
 "tags": [
  "Amazon EMR",
  "Prometheus",
  "Node_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(node_uname_info{job=~\"$job\"}, service)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info{job=~\"$job\", service=~\"$service\"}, cluster_id)"
   },
   {
    "name": "cluster_role",
    "label": "Cluster Role",
    "query": "label_values(node_uname_info{job=~\"$job\", service=~\"$service\", cluster_id=~\"$cluster\"}, cluster_role)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\", service=~\"$service\", cluster_id=~\"$cluster\", cluster_role=~\"$cluster_role\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Resource Overview【JOB：$job】",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=~\"$job\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "Servers Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up {job=\"$job\", cluster_id=~'$cluster', instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', instance=~\"$instance\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Normalized System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)/count(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode='system'}) by (cluster_id, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', fstype!='tmpfs'}",
     "legendFormat": "Size"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"}-0",
     "legendFormat": "Available"
    },
    {
     "expr": "1- (node_filesystem_avail_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"} / node_filesystem_size_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job\", cluster_id=~'$cluster',  instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~\"$instance\", fstype!=\"tmpfs\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (cluster_id, instance) (irate(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', mode=\"idle\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum(node_memory_MemAvailable_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)) / (sum(node_memory_MemTotal_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~'$job', cluster_id=~'$cluster'} - node_memory_MemAvailable_bytes{job=~'$job',cluster_id=~'$cluster'})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~'$job',cluster_id=~'$cluster'})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_weighted_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Transmission Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Receive Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (cluster_id, instance) (irate(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"idle\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Normalized System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)/count(node_cpu_seconds_total{job=\"$job\",  cluster_id=~'$cluster', instance=~'$instance', mode='system'}) by (cluster_id, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"idle\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"system\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"user\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOWait Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"iowait\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Steal Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"steal\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Soft IRQ Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"softirq\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IRQ Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance', mode=\"irq\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NICE Mode CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance', mode=\"nice\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk I/O Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_weighted_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance)(rate(node_disk_written_bytes_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance)(rate(node_disk_read_bytes_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merged Write I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance)(rate(node_disk_writes_merged_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merged Read I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance)(rate(node_disk_reads_merged_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O Request Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " ((sum by (job, cluster_id, instance)(rate(node_disk_read_bytes_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])))+(sum by (job, cluster_id, instance)(rate(node_disk_written_bytes_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval]))))/((sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval]))) + (sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, cluster_id, instance)(rate(node_disk_write_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))/(sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, cluster_id, instance)(rate(node_disk_read_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))/(sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum(node_memory_MemAvailable_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)) / (sum(node_memory_MemTotal_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Paging",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]) + rate(node_vmstat_pswpout {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-node_memory_SwapFree_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}/node_memory_SwapTotal_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 89 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance'}/node_memory_CommitLimit_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OOM Kill",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 89 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": " rate(node_vmstat_oom_kill{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network I/O Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Network Up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_network_up {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', device=~\"eth.\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Transmission Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Receive Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 96 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transmission Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Receive Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 102 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transmission Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 102 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_errs_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Receive Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transmission Drop",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_drop_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Receive Drop",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "File System Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Disk Space Used",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', fstype!='tmpfs'}",
     "legendFormat": "Size"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"}-0",
     "legendFormat": "Available"
    },
    {
     "expr": "1- (node_filesystem_avail_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"} / node_filesystem_size_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_open_fds {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}/ process_max_fds {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File System Device Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_filesystem_device_error {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}